### ISSUE TITLE
Still getting "missing artifacts: deploy" with Berksfile

### ISSUE THREAD

**Issue by asross** [joeyAghion/opsworks_delayed_job#16] opened 2016-02-10 18:43 UTC
I would like to point my Berksfile to this repository, not one of its numerous forks, but per the issues encountered in https://github.com/joeyAghion/opsworks_delayed_job/issues/8, it doesn't work on Opsworks unless you remove `depends 'deploy'` from `metadata.rb`. And everything seems to work fine without it.

Could you explain under what conditions the `depends` line is necessary, and if it's possible to detect when those conditions are met programmatically, only conditionally invoke it?

**Comment by joeyAghion** [comment] 2016-02-10 19:00
If I recall correctly, the `depends 'deploy'` addition was necessary to avoid errors when executing custom recipes within Opsworks. The `deploy` recipe is included by this custom cookbook's own recipes (e.g., [here](https://github.com/joeyAghion/opsworks_delayed_job/blob/3e6519ac38b3c106a5787d48fdded7edcae01b8c/recipes/deploy.rb#L3)), and this line would error when the dependency wasn't made explicit in `metadata.rb`.

However, it's possible that this behavior was associated with an older Chef version. We're upgraded a few times since then and are now on 11.10. I can re-test if that helps.

**Comment by asross** [comment] 2016-02-10 19:02
We're on 11.10 now too. For right now we're going to stick with my fork, but if you also find the change necessary when running `update_custom_cookbooks`, I can make a pull request or you can make the update.

**Comment by asross** [comment] 2016-02-10 19:07
We also have Opsworks set to manage berkshelf, and are using Berkshelf 3.2.0.

**Comment by joeyAghion** [comment] 2016-02-11 02:59
I confirmed that the dependency is no longer necessary with Chef 11.10.

(Fixed by 14829c984d7bb0fdf1f5a973d6a4d0d49c755a59 and v0.7.)

**Closed by joeyAghion** 2016-02-11 02:59 UTC

**Comment by asross** [comment] 2016-02-11 04:25
Thanks!
